let editingProductId=null;
function spawnParticles(){const c=document.getElementById('particles');if(!c)return;for(let i=0;i<25;i++){const p=document.createElement('div');p.className='particle';p.style.cssText=`left:${Math.random()*100}%;width:2px;height:2px;animation-duration:${Math.random()*12+8}s;animation-delay:${Math.random()*10}s;background:rgba(0,255,136,.7)`;c.appendChild(p);}}
function money(n){return Number(n||0).toLocaleString('en-PK');}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function showPage(id,el){document.querySelectorAll('.page-section').forEach(s=>s.classList.remove('active'));document.querySelectorAll('.sidebar-item').forEach(i=>i.classList.remove('active'));document.getElementById('page-'+id).classList.add('active');if(el)el.classList.add('active');topbarTitle.textContent={dashboard:'Dashboard',products:'Product Management',orders:'Order Management'}[id]||id;if(id==='dashboard')loadDashboard();if(id==='products')loadProductsAdmin();if(id==='orders')loadOrdersAdmin();}
async function guardAdmin(){try{let session=Auth.getSession(); if(Auth.isLoggedIn() && !session){session=await Auth.me();localStorage.setItem('th_session',JSON.stringify(session));} if(!session||session.role!=='admin')throw new Error('Admin access required');loginGuard.style.display='none';adminApp.style.display='flex';return true;}catch{loginGuard.style.display='block';adminApp.style.display='none';return false;}}
function statCard(label,value,icon='📊'){return `<div class="stat-box green"><div class="stat-label"><span>${icon}</span>${label}</div><div class="stat-value green">${value}</div></div>`;}
function renderBars(monthly=[]){const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];const max=Math.max(1,...monthly.map(m=>m.orders));return monthly.map(m=>`<div class="bar-item"><div class="bar" style="height:${Math.max(6,(m.orders/max)*100)}%" title="${months[m.month-1]}: ${m.orders} orders"></div><span>${months[m.month-1]}</span></div>`).join('');}
function renderStatusChart(dist={}){const total=Math.max(1,Object.values(dist).reduce((a,b)=>a+b,0));return Object.entries(dist).map(([k,v])=>`<div class="status-row"><span>${k}</span><div class="status-track"><i style="width:${(v/total)*100}%"></i></div><strong>${v}</strong></div>`).join('');}
async function loadDashboard(){try{const s=await Stats.admin();const items=[['Total Products',s.total_products,'📦'],['Total Orders',s.total_orders,'🧾'],['Pending Orders',s.pending_orders,'⏳'],['Confirmed Orders',s.confirmed_orders,'✅'],['Processing Orders',s.processing_orders,'⚙️'],['Shipped Orders',s.shipped_orders,'🚚'],['Delivered Orders',s.delivered_orders,'🏁'],['Cancelled Orders',s.cancelled_orders,'❌'],['Today\'s Orders',s.today_orders,'📅'],['Monthly Orders',s.monthly_orders,'🗓️'],['Total Revenue',`PKR ${money(s.revenue)}`,'💰']];statsGrid.innerHTML=items.map(x=>statCard(...x)).join('');recentOrders.innerHTML=(s.recent_orders||[]).map(o=>`<tr><td>${esc(o.order_id)}</td><td>${esc(o.customer_name)}</td><td>${esc(o.product_name)}</td><td>PKR ${money(o.total_price)}</td><td><span class="pill pill-approved">${esc(o.order_status)}</span></td><td>${new Date(o.created_at).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="6">No orders yet.</td></tr>';monthlyOrdersChart.innerHTML=renderBars(s.monthly||[]);monthlySales.innerHTML='PKR '+money((s.monthly||[]).reduce((a,b)=>a+(b.sales||0),0));statusChart.innerHTML=renderStatusChart(s.status_distribution||{});}catch(e){showToast(e.message,'error');}}
async function loadProductsAdmin(){try{const active=await Products.list({status:'active',limit:500});const inactive=await Products.list({status:'inactive',limit:500}).catch(()=>({products:[]}));const rows=[...(active.products||[]),...(inactive.products||[])];productsTable.innerHTML=rows.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>PKR ${money(p.price)}</td><td>${p.stock}</td><td><span class="verified-label">My Store • Verified</span></td><td><button class="btn-small" onclick='editProduct(${JSON.stringify(p).replace(/'/g,"&#39;")})'>Edit</button><button class="btn-small danger" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No products.</td></tr>';}catch(e){showToast(e.message,'error');}}
function editProduct(p){editingProductId=p.id;pName.value=p.name;pCat.value=p.category;pPrice.value=p.price;pStock.value=p.stock;pImage.value=p.image||'';pStatus.value=p.status||'active';pDesc.value=p.description;productFormTitle.textContent='Edit Product';}
function resetProductForm(){editingProductId=null;['pName','pCat','pPrice','pStock','pImage','pDesc'].forEach(id=>document.getElementById(id).value='');pStatus.value='active';productFormTitle.textContent='Add Product';}
async function saveProduct(){const payload={name:pName.value.trim(),category:pCat.value.trim(),price:Number(pPrice.value),stock:Number(pStock.value),image:pImage.value.trim()||null,description:pDesc.value.trim(),status:pStatus.value};if(!payload.name||!payload.category||!payload.description||payload.price<0||payload.stock<0)return showToast('Fill valid product name, category, price, stock and description.','error');try{if(editingProductId)await Products.update(editingProductId,payload);else await Products.create(payload);showToast('Product saved.');resetProductForm();loadProductsAdmin();loadDashboard();}catch(e){showToast(e.message,'error');}}
async function deleteProduct(id){if(!confirm('Delete this product?'))return;try{await Products.delete(id);showToast('Product deleted.');loadProductsAdmin();loadDashboard();}catch(e){showToast(e.message,'error');}}
async function loadOrdersAdmin(){try{const orders=await Orders.list();ordersTable.innerHTML=orders.map(o=>`<tr><td>${esc(o.order_id)}</td><td>${esc(o.customer_name)}</td><td>${esc(o.phone)}</td><td>${esc(o.email||'-')}</td><td>${esc(o.city)}<br><small>${esc(o.address)}</small></td><td>${esc(o.product_name)}</td><td>${o.quantity}</td><td>PKR ${money(o.total_price)}</td><td>${esc(o.notes||'-')}</td><td><span class="pill pill-approved">${esc(o.order_status)}</span></td><td>${new Date(o.created_at).toLocaleString()}</td><td><select class="status-select" onchange="setOrderStatus('${o.order_id}',this.value)"><option value="">Update</option>${['confirmed','processing','shipped','delivered','cancelled'].map(st=>`<option value="${st}">${st}</option>`).join('')}</select><button class="btn-small danger" onclick="deleteOrder('${o.order_id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="12">No orders yet.</td></tr>';}catch(e){showToast(e.message,'error');}}
async function setOrderStatus(id,status){if(!status)return;try{await Orders.setStatus(id,status);showToast('Order updated.');loadOrdersAdmin();loadDashboard();}catch(e){showToast(e.message,'error');}}
async function deleteOrder(id){if(!confirm('Delete this order?'))return;try{await Orders.delete(id);showToast('Order deleted.');loadOrdersAdmin();loadDashboard();}catch(e){showToast(e.message,'error');}}
document.addEventListener('DOMContentLoaded',async()=>{spawnParticles();if(window.topbarDate)topbarDate.textContent=new Date().toLocaleDateString('en-PK',{weekday:'short',day:'numeric',month:'short',year:'numeric'});if(await guardAdmin()){loadDashboard();loadProductsAdmin();}});
